name: eadukalthedi
description: "A new Flutter project."

# Prevents accidental publication to pub.dev.
publish_to: 'none'

# Application version details.
version: 1.0.0+1

# Flutter SDK version.
environment:
  sdk: '>=3.0.0 <4.0.0'

# Application dependencies.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  gap: ^3.0.1
  page_transition: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  flutter_gen: ^5.8.0

# Development dependencies for testing and linting.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Adding assets.
  assets:
    - assets/pngs/

  # Adding custom fonts if needed.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
